package defpackage;

import com.google.android.gms.auth.api.proxy.AuthApiStatusCodes;
import com.google.api.client.http.HttpStatusCodes;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-307f6cdf5dad069c1280d5a258b34c4733645288135c3d5b66a2837f479f7eef */
/* JADX INFO: loaded from: classes.dex */
public abstract class e05 {
    public static final d05 A;
    public static final d05 A0;
    public static final d05 B;
    public static final d05 B0;
    public static final d05 C;
    public static final d05 C0;
    public static final d05 D;
    public static final d05 D0;
    public static final d05 E;
    public static final d05 E0;
    public static final d05 F;
    public static final d05 F0;
    public static final d05 G;
    public static final d05 G0;
    public static final d05 H;
    public static final d05 H0;
    public static final d05 I;
    public static final d05 I0;
    public static final d05 J;
    public static final d05 J0;
    public static final d05 K;
    public static final d05 K0;
    public static final d05 L;
    public static final d05 L0;
    public static final d05 M;
    public static final d05 M0;
    public static final d05 N;
    public static final d05 N0;
    public static final d05 O;
    public static final d05 O0;
    public static final d05 P;
    public static final d05 P0;
    public static final d05 Q;
    public static final d05 Q0;
    public static final d05 R;
    public static final d05 R0;
    public static final d05 S;
    public static final d05 S0;
    public static final d05 T;
    public static final d05 T0;
    public static final d05 U;
    public static final d05 U0;
    public static final d05 V;
    public static final d05 V0;
    public static final d05 W;
    public static final d05 W0;
    public static final d05 X;
    public static final d05 X0;
    public static final d05 Y;
    public static final d05 Y0;
    public static final d05 Z;
    public static final d05 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final d05 a0;
    public static final d05 a1;
    public static final d05 b;
    public static final d05 b0;
    public static final d05 b1;
    public static final d05 c;
    public static final d05 c0;
    public static final d05 c1;
    public static final d05 d;
    public static final d05 d0;
    public static final d05 d1;
    public static final d05 e;
    public static final d05 e0;
    public static final d05 e1;
    public static final d05 f;
    public static final d05 f0;
    public static final d05 f1;
    public static final d05 g;
    public static final d05 g0;
    public static final d05 g1;
    public static final d05 h;
    public static final d05 h0;
    public static final d05 h1;
    public static final d05 i;
    public static final d05 i0;
    public static final d05 i1;
    public static final d05 j;
    public static final d05 j0;
    public static final d05 j1;
    public static final d05 k;
    public static final d05 k0;
    public static final d05 l;
    public static final d05 l0;
    public static final d05 m;
    public static final d05 m0;
    public static final d05 n;
    public static final d05 n0;
    public static final d05 o;
    public static final d05 o0;
    public static final d05 p;
    public static final d05 p0;
    public static final d05 q;
    public static final d05 q0;
    public static final d05 r;
    public static final d05 r0;
    public static final d05 s;
    public static final d05 s0;
    public static final d05 t;
    public static final d05 t0;

    /* JADX INFO: renamed from: u, reason: collision with root package name */
    public static final d05 f77u;
    public static final d05 u0;
    public static final d05 v;
    public static final d05 v0;
    public static final d05 w;
    public static final d05 w0;
    public static final d05 x;
    public static final d05 x0;
    public static final d05 y;
    public static final d05 y0;
    public static final d05 z;
    public static final d05 z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, ky4.D, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, pr3.q, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, yv4.o, false);
        e = a("measurement.config.cache_time", 86400000L, zv4.t, false);
        f = a("measurement.config.url_scheme", "https", yv4.z, false);
        g = a("measurement.config.url_authority", "app-measurement.com", zv4.E, false);
        h = a("measurement.upload.max_bundles", 100, yv4.K, false);
        i = a("measurement.upload.max_batch_size", 65536, zv4.P, false);
        j = a("measurement.upload.max_bundle_size", 65536, ky4.r, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, ky4.x, false);
        l = a("measurement.upload.max_events_per_day", 100000, ny4.B, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, pr3.t, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, ls3.y, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, pr3.f264u, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, ls3.z, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, pr3.v, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", ls3.A, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", pr3.w, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", ls3.B, false);
        f77u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", pr3.x, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, ls3.C, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, zv4.o, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, yv4.p, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, zv4.p, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, yv4.q, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, zv4.q, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, yv4.r, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, zv4.r, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, yv4.s, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, zv4.s, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, yv4.t, false);
        G = a("measurement.upload.backoff_period", 43200000L, yv4.f429u, false);
        a("measurement.upload.window_interval", 3600000L, zv4.f446u, false);
        H = a("measurement.upload.interval", 3600000L, yv4.v, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, zv4.v, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, yv4.w, false);
        K = a("measurement.upload.minimum_delay", 500L, zv4.w, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, yv4.x, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, zv4.x, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, yv4.y, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, zv4.y, false);
        P = a("measurement.upload.retry_time", 1800000L, zv4.z, false);
        Q = a("measurement.upload.retry_count", 6, yv4.A, false);
        R = a("measurement.upload.max_queue_time", 518400000L, zv4.A, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, yv4.B, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, zv4.B, false);
        U = a("measurement.audience.filter_result_max_count", Integer.valueOf(HttpStatusCodes.STATUS_CODE_OK), yv4.C, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, zv4.C, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, yv4.D, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.test_boolean_flag", bool, zv4.D, false);
        b0 = a("measurement.test.test_string_flag", "---", yv4.E, false);
        c0 = a("measurement.test.test_long_flag", -1L, yv4.F, false);
        a("measurement.test.test_cached_long_flag", -1L, zv4.F, true);
        d0 = a("measurement.test.test_int_flag", -2, yv4.G, false);
        e0 = a("measurement.test.test_double_flag", Double.valueOf(-3.0d), zv4.G, false);
        a("measurement.experiment.max_ids", 50, yv4.H, false);
        f0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, zv4.H, false);
        g0 = a("measurement.upload.max_event_parameter_value_length", 500, yv4.I, true);
        h0 = a("measurement.max_bundles_per_iteration", 100, zv4.I, false);
        i0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, yv4.J, false);
        j0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, zv4.J, false);
        k0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, zv4.K, false);
        l0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, yv4.L, false);
        m0 = a("measurement.rb.attribution.uri_scheme", "https", zv4.L, false);
        n0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", yv4.M, false);
        o0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", zv4.M, false);
        p0 = a("measurement.session.engagement_interval", 3600000L, yv4.N, false);
        q0 = a("measurement.rb.attribution.app_allowlist", "", zv4.N, false);
        r0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", yv4.O, false);
        s0 = a("measurement.rb.attribution.event_params", "value|currency", zv4.O, false);
        t0 = a("measurement.rb.attribution.query_parameters_to_remove", "", yv4.P, false);
        u0 = a("measurement.rb.attribution.max_queue_time", 864000000L, yv4.Q, false);
        v0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, zv4.Q, false);
        w0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, yv4.R, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, zv4.R, false);
        x0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, ky4.o, false);
        Boolean bool2 = Boolean.TRUE;
        y0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, ny4.o, false);
        z0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, ky4.p, false);
        A0 = a("measurement.rb.attribution.notify_app_delay_millis", Integer.valueOf(AuthApiStatusCodes.AUTH_API_INVALID_CREDENTIALS), ny4.p, false);
        a("measurement.config.default_flag_values", bool2, ky4.q, false);
        B0 = a("measurement.upload.diagnostic_upload_interval", 3600000L, ny4.q, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, ny4.r, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, ky4.s, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, ny4.s, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, ky4.t, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, ny4.t, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, ky4.f175u, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, ky4.v, false);
        K0 = a("measurement.service.store_null_safelist", bool2, ny4.f229u, false);
        L0 = a("measurement.service.store_safelist", bool2, ky4.w, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, ny4.v, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, ny4.w, true);
        O0 = a("measurement.rb.attribution.service", bool2, ky4.y, true);
        P0 = a("measurement.rb.attribution.client2", bool2, ny4.x, true);
        Q0 = a("measurement.rb.attribution.uuid_generation", bool2, ky4.z, false);
        R0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, ny4.y, false);
        S0 = a("measurement.client.sessions.enable_fix_background_engagement", bool2, ny4.E, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, ky4.A, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, ny4.z, false);
        T0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, ky4.B, false);
        U0 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, ny4.A, false);
        V0 = a("measurement.experiment.enable_passthrough_experiment_reporting", bool2, ky4.C, false);
        W0 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, ls3.s, false);
        X0 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, pr3.o, false);
        Y0 = a("measurement.service.fix_stop_bundling_bug", bool2, ls3.f190u, false);
        Z0 = a("measurement.gbraid_campaign.stop_lgclid", bool, ky4.E, false);
        a1 = a("measurement.gbraid_campaign.deep_link_url", bool, ny4.C, false);
        b1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", ls3.v, false);
        c1 = a("measurement.edpb.service", bool, pr3.p, false);
        d1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", pr3.r, false);
        e1 = a("measurement.robust_time_source_2", bool, ky4.F, false);
        f1 = a("measurement.manual_iap_logging.client_service", bool, ny4.D, false);
        g1 = a("measurement.dsid_consent_only.app_allowlist1", "", ls3.w, false);
        h1 = a("measurement.dsid_consent_only.app_allowlist2", "", pr3.s, false);
        i1 = a("measurement.dsid_consent_only.app_allowlist3", "", ls3.x, false);
        j1 = a("measurement.diagnostics.enabled", bool, ls3.t, false);
    }

    public static d05 a(String str, Object obj, mu4 mu4Var, boolean z2) {
        d05 d05Var = new d05(str, obj, mu4Var);
        if (z2) {
            a.add(d05Var);
        }
        return d05Var;
    }
}
