package defpackage;

/* JADX INFO: compiled from: r8-map-id-307f6cdf5dad069c1280d5a258b34c4733645288135c3d5b66a2837f479f7eef */
/* JADX INFO: loaded from: classes.dex */
public abstract class p44 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final pb1 D;
    public static final vg1 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final pb1 I;
    public static final vg1 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final pb1 N;
    public static final vg1 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final pb1 S;
    public static final vg1 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final pb1 X;
    public static final vg1 Y;
    public static final long Z;
    public static final vg1 a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final pb1 c0;
    public static final long d;
    public static final vg1 d0;
    public static final pb1 e;
    public static final long e0;
    public static final vg1 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final pb1 h0;
    public static final long i;
    public static final vg1 i0;
    public static final pb1 j;
    public static final long j0;
    public static final vg1 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final pb1 m0;
    public static final long n;
    public static final vg1 n0;
    public static final pb1 o;
    public static final long o0;
    public static final vg1 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final pb1 r0;
    public static final long s;
    public static final vg1 s0;
    public static final pb1 t;
    public static final long t0;

    /* JADX INFO: renamed from: u, reason: collision with root package name */
    public static final vg1 f255u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final pb1 w0;
    public static final long x;
    public static final pb1 y;
    public static final vg1 z;

    static {
        pb1 pb1Var = d54.a;
        vg1 vg1Var = ra1.b;
        a = vg1Var;
        b = on4.C(24.0d);
        c = on4.D(16);
        d = on4.C(0.5d);
        pb1 pb1Var2 = d54.b;
        e = pb1Var2;
        f = vg1Var;
        g = on4.C(20.0d);
        h = on4.D(14);
        i = on4.C(0.2d);
        j = pb1Var2;
        k = vg1Var;
        l = on4.C(16.0d);
        m = on4.D(12);
        n = on4.C(0.4d);
        o = pb1Var2;
        p = vg1Var;
        q = on4.C(64.0d);
        r = on4.D(57);
        long jC = on4.C(0.2d);
        dy3[] dy3VarArr = cy3.b;
        long j2 = jC & 1095216660480L;
        if (j2 == 0) {
            cr1.a("Cannot perform operation for Unspecified type.");
        }
        s = on4.F(-cy3.c(jC), j2);
        t = pb1Var2;
        f255u = vg1Var;
        v = on4.C(52.0d);
        w = on4.D(45);
        x = on4.C(0.0d);
        y = pb1Var2;
        z = vg1Var;
        A = on4.C(44.0d);
        B = on4.D(36);
        C = on4.C(0.0d);
        D = pb1Var2;
        E = vg1Var;
        F = on4.C(40.0d);
        G = on4.D(32);
        H = on4.C(0.0d);
        I = pb1Var2;
        J = vg1Var;
        K = on4.C(36.0d);
        L = on4.D(28);
        M = on4.C(0.0d);
        N = pb1Var2;
        O = vg1Var;
        P = on4.C(32.0d);
        Q = on4.D(24);
        R = on4.C(0.0d);
        S = pb1Var2;
        T = vg1Var;
        U = on4.C(20.0d);
        V = on4.D(14);
        W = on4.C(0.1d);
        pb1 pb1Var3 = d54.a;
        X = pb1Var3;
        Y = vg1Var;
        Z = on4.C(16.0d);
        a0 = on4.D(12);
        b0 = on4.C(0.5d);
        c0 = pb1Var3;
        d0 = vg1Var;
        e0 = on4.C(16.0d);
        f0 = on4.D(11);
        g0 = on4.C(0.5d);
        h0 = pb1Var3;
        i0 = vg1Var;
        j0 = on4.C(28.0d);
        k0 = on4.D(22);
        l0 = on4.C(0.0d);
        m0 = pb1Var2;
        n0 = vg1Var;
        o0 = on4.C(24.0d);
        p0 = on4.D(16);
        q0 = on4.C(0.2d);
        r0 = pb1Var3;
        s0 = vg1Var;
        t0 = on4.C(20.0d);
        u0 = on4.D(14);
        v0 = on4.C(0.1d);
        w0 = pb1Var3;
        on4.C(24.0d);
        on4.D(16);
        on4.C(0.15d);
        on4.C(20.0d);
        on4.D(14);
        on4.C(0.25d);
        on4.C(16.0d);
        on4.D(12);
        on4.C(0.4d);
        on4.C(64.0d);
        on4.D(57);
        on4.D(0);
        on4.C(52.0d);
        on4.D(45);
        on4.D(0);
        on4.C(44.0d);
        on4.D(36);
        on4.D(0);
        on4.C(40.0d);
        on4.D(32);
        on4.D(0);
        on4.C(36.0d);
        on4.D(28);
        on4.D(0);
        on4.C(32.0d);
        on4.D(24);
        on4.D(0);
        on4.C(20.0d);
        on4.D(14);
        on4.C(0.1d);
        on4.C(16.0d);
        on4.D(12);
        on4.C(0.5d);
        on4.C(16.0d);
        on4.D(11);
        on4.C(0.5d);
        on4.C(28.0d);
        on4.D(22);
        on4.D(0);
        on4.C(24.0d);
        on4.D(16);
        on4.C(0.15d);
        on4.C(20.0d);
        on4.D(14);
        on4.C(0.1d);
    }
}
